In [3]:
import numpy as np

In [4]:
dt = 1e-1
# The transition matrix (6x6).
F = np.eye(9)
F[0][3] = dt
F[1][4] = dt
F[2][5] = dt
F[0][6] = .5*dt**2
F[1][7] = .5*dt**2
F[2][8] = .5*dt**2
F[3][6] = dt
F[4][7] = dt
F[5][8] = dt
F

array([[1.   , 0.   , 0.   , 0.1  , 0.   , 0.   , 0.005, 0.   , 0.   ],
       [0.   , 1.   , 0.   , 0.   , 0.1  , 0.   , 0.   , 0.005, 0.   ],
       [0.   , 0.   , 1.   , 0.   , 0.   , 0.1  , 0.   , 0.   , 0.005],
       [0.   , 0.   , 0.   , 1.   , 0.   , 0.   , 0.1  , 0.   , 0.   ],
       [0.   , 0.   , 0.   , 0.   , 1.   , 0.   , 0.   , 0.1  , 0.   ],
       [0.   , 0.   , 0.   , 0.   , 0.   , 1.   , 0.   , 0.   , 0.1  ],
       [0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 1.   , 0.   , 0.   ],
       [0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 1.   , 0.   ],
       [0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 1.   ]])

In [5]:
x = np.ones((9,1))

In [6]:
for _ in range(10):
    x = F @ x
    print(x)

[[1.105]
 [1.105]
 [1.105]
 [1.1  ]
 [1.1  ]
 [1.1  ]
 [1.   ]
 [1.   ]
 [1.   ]]
[[1.22]
 [1.22]
 [1.22]
 [1.2 ]
 [1.2 ]
 [1.2 ]
 [1.  ]
 [1.  ]
 [1.  ]]
[[1.345]
 [1.345]
 [1.345]
 [1.3  ]
 [1.3  ]
 [1.3  ]
 [1.   ]
 [1.   ]
 [1.   ]]
[[1.48]
 [1.48]
 [1.48]
 [1.4 ]
 [1.4 ]
 [1.4 ]
 [1.  ]
 [1.  ]
 [1.  ]]
[[1.625]
 [1.625]
 [1.625]
 [1.5  ]
 [1.5  ]
 [1.5  ]
 [1.   ]
 [1.   ]
 [1.   ]]
[[1.78]
 [1.78]
 [1.78]
 [1.6 ]
 [1.6 ]
 [1.6 ]
 [1.  ]
 [1.  ]
 [1.  ]]
[[1.945]
 [1.945]
 [1.945]
 [1.7  ]
 [1.7  ]
 [1.7  ]
 [1.   ]
 [1.   ]
 [1.   ]]
[[2.12]
 [2.12]
 [2.12]
 [1.8 ]
 [1.8 ]
 [1.8 ]
 [1.  ]
 [1.  ]
 [1.  ]]
[[2.305]
 [2.305]
 [2.305]
 [1.9  ]
 [1.9  ]
 [1.9  ]
 [1.   ]
 [1.   ]
 [1.   ]]
[[2.5]
 [2.5]
 [2.5]
 [2. ]
 [2. ]
 [2. ]
 [1. ]
 [1. ]
 [1. ]]


In [7]:
# https://github.com/glucee/Multilateration

from scipy.optimize import minimize
import numpy as np

def gps_solve(distances_to_station, stations_coordinates):
	def error(x, c, r):
		return sum([(np.linalg.norm(x - c[i]) - r[i]) ** 2 for i in range(len(c))])
	l = len(stations_coordinates)
	print(l)
	S = sum(distances_to_station)
	print(stations_coordinates)
	print(distances_to_station)

	print(S)
	# compute weight vector for initial guess
	W = [((l - 1) * S) / (S - w) for w in distances_to_station]
	print(W,'W')
	# get initial guess of point location
	x0 = sum([W[i] * stations_coordinates[i] for i in range(l)]).reshape((3,1))
	# optimize distance from signal origin to border of spheres

	print('\n')
	print(x0, stations_coordinates, distances_to_station)

	return minimize(error, x0, args=(stations_coordinates, distances_to_station), method='Nelder-Mead').x

stations = list(np.array([[1,1,1], [-1,1,1], [-1,-1,-1], [1,-1,1]]))
distances_to_station = [np.sqrt(np.sqrt(2)**2 + 1**2) for _ in range(4)]
print(gps_solve(distances_to_station, stations))

4
[array([1, 1, 1]), array([-1,  1,  1]), array([-1, -1, -1]), array([ 1, -1,  1])]
[1.7320508075688774, 1.7320508075688774, 1.7320508075688774, 1.7320508075688774]
6.92820323027551
[4.0, 4.0, 4.0, 4.0] W


[[0.]
 [0.]
 [8.]] [array([1, 1, 1]), array([-1,  1,  1]), array([-1, -1, -1]), array([ 1, -1,  1])] [1.7320508075688774, 1.7320508075688774, 1.7320508075688774, 1.7320508075688774]
[ 0.00076176  0.00146544 -0.00109143]


In [8]:
stations

[array([1, 1, 1]),
 array([-1,  1,  1]),
 array([-1, -1, -1]),
 array([ 1, -1,  1])]

In [9]:
distances_to_station

[1.7320508075688774,
 1.7320508075688774,
 1.7320508075688774,
 1.7320508075688774]

In [12]:
H = np.zeros((3, 9))
H[0][0] = 1
H[1][1] = 1
H[2][2] = 1
H

array([[1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0.]])